### ISSUE TITLE
Login Not Working

### ISSUE THREAD

**Issue by DragoniteDD** [azuline/pixiv-api#10]
login not working, might be related to the website's recent update to accommodate apple login.

**Comment by EllangoK** [comment]
Same for me, can't login with username and password or refresh code.

**Comment by DreiPixel** [comment]
its basically this https://github.com/upbit/pixivpy/issues/140
its fixable tho

**Comment by azuline** [comment]
Thanks for the heads up, fixed.

**Comment by redfoxofdeath** [comment]
Does anybody know how to fix the login issue when compiled with pyinstaller? Client.login() causes a FileNotFoundError:
```
Traceback (most recent call last):
  File "threading.py", line 926, in _bootstrap_inner
  File "services.py", line 45, in run
  File "services.py", line 24, in login
  File "pixivapi\client.py", line 65, in __init__
  File "cloudscraper\__init__.py", line 748, in create_scraper
  File "cloudscraper\__init__.py", line 138, in __init__
  File "cloudscraper\user_agent\__init__.py", line 20, in __init__
  File "cloudscraper\user_agent\__init__.py", line 74, in loadUserAgent
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\rfod\\Documents\\GitHub\\art-collections\\ArtCollections\\cloudscraper\\user_agent\\browsers.json'
```

**Comment by DreiPixel** [comment]
@redfoxofdeath not a issue with this program but a quick google: https://stackoverflow.com/questions/62668742/adding-pip-libraries-in-pyinstaller-to-create-an-exe-file-for-my-script
